### ISSUE TITLE
pip does not install the last version of the code 

### ISSUE THREAD

**Issue by vserret** [opendifferentialprivacy/smartnoise-sdk#316] opened 2020-11-25 08:53 UTC
Hi, 
When I try to run : 
`iris = Table("dbo", "iris", [
    Float("sepal length (cm)", 4, 8),
    Float("sepal width (cm)", 2, 5),
    Float("petal length (cm)", 1, 7),
    Float("petal width (cm)", 0, 3)
], 150)`
from the script here https://github.com/opendifferentialprivacy/smartnoise-sdk#script, I get: 
`AttributeError: 'DataFrame' object has no attribute 'm_tables'`
I have also errors with the following lines. 
I guess that when I run pip install, I do not get the last version of your code.

**Comment by joshua-oss** [comment] 2020-11-25 22:09
Hi, thanks for reporting this.  It looks like the sample was not updated, since execute_private_query now returns a Dataframe, so there is no need to convert the result to a DataFrame after the call to execute_private query.  Can you check that the following runs (just replacing that line with df = rowset):

`import sklearn.datasets
import pandas as pd

from opendp.smartnoise.sql import execute_private_query, PandasReader
from opendp.smartnoise.metadata import CollectionMetadata
from opendp.smartnoise.metadata.collection import Table, Float

sklearn_dataset = sklearn.datasets.load_iris()
sklearn_df = pd.DataFrame(data=sklearn_dataset.data, columns=sklearn_dataset.feature_names)


iris = Table("dbo", "iris", [
    Float("sepal length (cm)", 4, 8),
    Float("sepal width (cm)", 2, 5),
    Float("petal length (cm)", 1, 7),
    Float("petal width (cm)", 0, 3)
], 150)
schema = CollectionMetadata([iris], "csv")

reader = PandasReader(sklearn_df, schema)
rs = reader.execute('SELECT AVG("petal width (cm)") FROM dbo.iris')
rowset = execute_private_query(reader, schema, 0.3, 'SELECT AVG("petal width (cm)") FROM dbo.iris')
df = rowset
with pd.option_context('display.max_rows', None, 'display.max_columns', 3): print(df)`

**Comment by vserret** [comment] 2020-11-26 11:05
Hi thanks for your answer. No it doesn't work. 
I have an error when I run 
`iris = Table("dbo", "iris", [
    Float("sepal length (cm)", 4, 8),
    Float("sepal width (cm)", 2, 5),
    Float("petal length (cm)", 1, 7),
    Float("petal width (cm)", 0, 3)
], 150)`
I get : 

`TypeError                                 Traceback (most recent call last)
<ipython-input-20-777b7ec46c19> in <module>
----> 1 iris = Table("dbo", "iris", [
      2     Float("sepal length (cm)", 4, 8),
      3     Float("sepal width (cm)", 2, 5),
      4     Float("petal length (cm)", 1, 7),
      5     Float("petal width (cm)", 0, 3)

/usr/local/lib/python3.8/site-packages/opendp/smartnoise/metadata/collection.py in __init__(self, schema, name, rowcount, columns, row_privacy, max_ids, sample_max_ids, rows_exact)
     73         self.sample_max_ids = sample_max_ids
     74         self.rows_exact = rows_exact
---> 75         self.m_columns = dict([(c.name, c) for c in columns])
     76         self.compare = None
     77     def __getitem__(self, colname):

TypeError: 'int' object is not iterable`

But when I run 
`iris = Table("dbo", "iris", 150, [
    Float("sepal length (cm)", 4, 8),
    Float("sepal width (cm)", 2, 5),
    Float("petal length (cm)", 1, 7),
    Float("petal width (cm)", 0, 3)
])`
It works

**Comment by joshua-oss** [comment] 2020-11-27 03:11
OK, that definitely looks like you have an older version.  Can you try `pip show opendp-smartnoise`?  It should show version 0.1.1.  If you have an older version, you can upgrade with `pip install --upgrade opendp-smartnoise`.

You can also uninstall (with `pip uninstall opendp-smartnoise`) and then reinstall.

**Comment by vserret** [comment] 2020-11-27 09:11
I have `Version: 0.1.1` even when I upgrade it but since I work on Google Colab it should install the last version

**Comment by joshua-oss** [comment] 2020-11-27 16:34
This error reproduces in Colab for me.  It looks like a problem with out wheel file.  I'll update when we verify and fix.

**Comment by saisaravanan** [comment] 2021-01-12 18:24
I m facing the same issue when I follow the pip install <package name>. I tried checking out git to overwrite the site-package/folders. I was able to get rid of it but ended in a sql syntax error for all basic queries being modified by smartnoise. 
Is some mismatch in version causing this?
```
pandasql.sqldf.PandaSQLException: (sqlite3.OperationalError) near "(": syntax error
[SQL: SELECT COUNT ( DISTINCT primary_key ) AS keycount, SUM ( petal_width__0_cm_1_ ) AS sum_petal_width__0_cm_1_, COUNT ( petal_width__0_cm_1_ ) AS count_petal_width__0_cm_1_ FROM ( SELECT *, ROW_NUMBER ( ) OVER ( PARTITION BY primary_key ORDER BY RANDOM ( ) ) AS row_num FROM ( SELECT primary_key AS primary_key, CASE WHEN petal_width__0_cm_1_ < 0 THEN 0 WHEN petal_width__0_cm_1_ > 3 THEN 3 ELSE  petal_width__0_cm_1_ END AS petal_width__0_cm_1_ FROM df_for_diffpriv1234 ) AS clamped ) AS per_key_random WHERE per_key_random.row_num <= 1]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by eedeleon** [comment] 2021-01-22 07:35
Keeping the other thread alive for the sqlite issue. closing this one since we updated the package on pypi

**Closed by eedeleon** 2021-01-22 07:35 UTC
